/**
 * Writes public/media/README.md: every media slot on the site, its ratio,
 * and the file to supply. Run with `npm run media:manifest`.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { services } from "../src/content/services";
import { home } from "../src/content/site";
import { story } from "../src/content/story";
import { team } from "../src/content/team";
import type { Ratio, Visual } from "../src/content/types";
import { work } from "../src/content/work";

const SIZE: Record<Ratio, string> = {
  "9:16": "1080 × 1920",
  "4:5": "1080 × 1350",
  "1:1": "1080 × 1080",
  "16:9": "1920 × 1080",
};

type Row = { visual: Visual; where: string; file: string };

const rows: Row[] = [];
const add = (visual: Visual, where: string, file: string) => rows.push({ visual, where, file });

home.hero.feed.forEach((post, i) =>
  add(post.visual, `Home hero feed, post ${i + 1}`, "src/content/site.ts"),
);
story.forEach((c) => add(c.visual, `Story, ${c.year}`, "src/content/story.ts"));
services.forEach((s) => add(s.preview, `Service preview, ${s.name}`, "src/content/services.ts"));
work.forEach((c) => {
  add(c.cover, `${c.client}, cover`, "src/content/work.ts");
  c.gallery.forEach((v, i) => add(v, `${c.client}, gallery ${i + 1}`, "src/content/work.ts"));
});
team.forEach((m) => add(m.portrait, `Team, ${m.name}`, "src/content/team.ts"));

const esc = (s: string) => s.replace(/\|/g, "\|");
const table = rows
  .map(({ visual: v, where, file }) => {
    const kind = v.kind === "video" ? "Video" : "Image";
    const status = v.src ? "Supplied" : "Placeholder";
    return `| \`${v.id}\` | ${esc(where)} | ${v.ratio} | ${kind} | ${SIZE[v.ratio]} | ${esc(v.label)} | ${status} | \`${file}\` |`;
  })
  .join("\n");

const doc = `# Media slots

Generated by \`npm run media:manifest\` from \`src/content/\`. Don't edit by hand.

Every image and video on the site is a \`MediaSlot\`. Until a slot has a \`src\`, it renders an
art-directed placeholder: the tone fill, film grain, and the label below describing the asset
that belongs there.

## Replacing a placeholder

1. Export the asset at the recommended size (2× the largest rendered size, so it stays sharp on
   high-density screens).
2. Save it here as \`/public/media/<slot id>.<ext>\`. For example, \`story-2015.jpg\`.
3. In the content file listed for that slot, add \`src: "/media/<slot id>.<ext>"\` to the visual,
   and rewrite \`alt\` to describe what the final asset actually shows.
4. For video slots, also add a poster frame: \`poster: "/media/<slot id>-poster.jpg"\`. The type
   checker won't accept a video \`src\` without one.
5. Run \`npm run media:manifest\` to refresh this file.

## Formats

- **Images:** JPG or PNG at the size below. \`next/image\` serves AVIF and WebP versions automatically.
- **Video:** MP4 (H.264), muted, 30fps, under 4 MB where possible, plus a JPG poster at the same
  size. Video plays only while on screen and never autoplays under reduced motion.

## Slots (${rows.length})

| Slot id | Where it appears | Ratio | Kind | Recommended size (px) | Intended asset | Status | Content file |
|---|---|---|---|---|---|---|---|
${table}
`;

writeFileSync(join(process.cwd(), "public", "media", "README.md"), doc);
console.log(`Wrote public/media/README.md with ${rows.length} slots.`);
